global:
  slack_api_url: "https://hooks.slack.com/services/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"
route:
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 10m
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - channel: "#alerts"
        icon_emoji: ":bell:"
        send_resolved: true
        text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}\nmessage: {{ .CommonAnnotations.message }}"
