export const GET_CHATS_BEGIN = "GET_CHATS_BEGIN";
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const GET_CHATS_ERROR = "GET_CHATS_ERROR";

export const GET_FRIENDS_BEGIN = "GET_FRIENDS_BEGIN";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR";
