apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-db
  template:
    metadata:
      labels:
        app: main-db
    spec:
      containers:
        - name: main-db
          image: crawan/main-db
          #////imagePullPolicy: Never
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: main-db-srv
spec:
  selector:
    app: main-db
  ports:
    - name: main-app-db
      protocol: TCP
      port: 5432
      targetPort: 5432
## Trigger mains service db file
