export const GET_CHATS_BEGIN = "GET_CHATS_BEGIN";
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const GET_CHATS_ERROR = "GET_CHATS_ERROR";

export const SET_CURRENT_CHAT_BEGIN = "SET_CURRENT_CHAT_BEGIN";
export const SET_CURRENT_CHAT_SUCCESS = "SET_CURRENT_CHAT_SUCCESS";
export const SET_CURRENT_CHAT_ERROR = "SET_CURRENT_CHAT_ERROR";

export const GET_FRIENDS_BEGIN = "GET_FRIENDS_BEGIN";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR";
